#
# .gitlab-ci.yml
#
# This builds a Docker image and tags it as the latest for its branch.
# After building, it will trigger a deployment pipeline in another repo.
#
# Reference:
#   - https://docs.gitlab.com/ee/ci/yaml/
#   - https://docs.gitlab.com/ee/ci/multi_project_pipelines.html
#
# CI Variables:
#   PUBSWH_SERVICES_IMAGE
#     Should be the full value of the Docker image to produce. This should include the full registry address.
#     This variable is sent to the deployment trigger.
#
#   PUBSWH_SERVICES_IMAGE_TAG
#     The Docker image tag. The default is to use the branch:short_sha
#     This variable is sent to the deployment trigger.
#
#   MAVEN_IMAGE
#     The Docker image name for maven. Used by the Docker image build for the Maven image source.
#
#   OPENJDK_IMAGE
#     The Docker image name for OpenJDK. Used by the Docker image build for the OpenJDK image source.
#
#   DEPLOY_TRIGGER_REF
#     Set on the individual deployment jobs below. This is the branch name to trigger on the deployment pipeline.
#
#   DEPLOY_TRIGGER_VARS
#     Space-delimited list of variables to pass along with the deployment trigger.
#     This is used to pass the PUBSWH_SERVICES_IMAGE and PUBSWH_SERVICES_IMAGE_TAG variables along.
#
include:
  - project: 'sas/ops/gitlab-ci-pipeline'
    file: '/build/docker.yml'
  - project: 'sas/ops/gitlab-ci-pipeline'
    file: '/deploy/api_trigger.yml'

stages:
  - docker_build
  - docker_tag_latest
  - deploy_trigger

variables:
  # This is passed to deployment
  PUBSWH_SERVICES_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  PUBSWH_SERVICES_IMAGE_TAG: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}

docker_build:
  variables:
    MAVEN_IMAGE: "code.chs.usgs.gov:5001/sas/ops/docker/base-images/maven:3.6.0-jdk-11-latest"
    # TODO: source internally
    OPENJDK_IMAGE: "usgswma/openjdk:11.0.4-jre-baa3726df925e679dedf110bc1dca29b323e5324"
    DOCKER_BUILD_ARGS: --build-arg MAVEN_IMAGE=${MAVEN_IMAGE} --build-arg OPENJDK_IMAGE=${OPENJDK_IMAGE}
  only:
    refs:
      - master

docker_tag_latest:
  only:
    refs:
      - master

trigger_deploy_development:
  extends: .deploy_trigger
  variables:
    DEPLOY_TRIGGER_VARS: PUBSWH_SERVICES_IMAGE PUBSWH_SERVICES_IMAGE_TAG
    ENVIRONMENT: development
    DEPLOY_TRIGGER_REF: master
  only:
    refs:
      - master
    variables:
      - DEPLOY_TRIGGER_TOKEN
      - DEPLOY_TRIGGER_URL

trigger_deploy_staging:
  extends: .deploy_trigger
  variables:
    DEPLOY_TRIGGER_VARS: PUBSWH_SERVICES_IMAGE PUBSWH_SERVICES_IMAGE_TAG
    ENVIRONMENT: staging
    DEPLOY_TRIGGER_REF: master
  only:
    refs:
      - master
    variables:
      - DEPLOY_TRIGGER_TOKEN
      - DEPLOY_TRIGGER_URL
