
sudo: true

language: java

services:
  - docker

jdk:
  - openjdk11

install: true

script:
  - docker network create pubsServices
  - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$TRAVIS_BUILD_DIR":/usr/src/mymaven -w /usr/src/mymaven --network=pubsServices -e TESTING_DATABASE_PORT=5432 -e TESTING_DATABASE_ADDRESS=pubsDatabase -e TESTING_DATABASE_NETWORK=pubsServices -e TESTING_CROSSREF_USERNAME=$TESTING_CROSSREF_USERNAME -e TESTING_CROSSREF_PASSWORD=$TESTING_CROSSREF_PASSWORD -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e CODACY_API_TOKEN=$CODACY_API_TOKEN -e CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN maven:3.6.2-jdk-11 mvn clean verify
  - docker network rm pubsServices

after_success:
  - bash <(curl -s https://codecov.io/bash)
