
version: '3'

services:
  pubs-services:
    build: .
    image: pubs-services
    networks:
      pubs:
        ipv4_address: ${PUBS_SERVICES_IPV4}
    ports:
      - ${PUBS_SERVICES_PORT}:8080
    environment:
      - COMMON_DATA_DIRECTORY=${COMMON_DATA_DIRECTORY}
      - APPLICATION_DATA_DIRECTORY=${APPLICATION_DATA_DIRECTORY}
    volumes:
      - ./secrets/common:${COMMON_DATA_DIRECTORY}
      - ./secrets/app:${APPLICATION_DATA_DIRECTORY}

networks:
  pubs:
    external:
      name: ${LOCAL_NETWORK_NAME}
