spring:
  activemq:
    broker-url: ${QUEUE_URL}
  datasource:
    url: jdbc:postgresql://${PUBS_DB_HOST}:${PUBS_DB_PORT}/${PUBS_DB_NAME}
    username: ${PUBS_DB_READ_ONLY_USERNAME}
    password: ${PUBS_DB_READ_ONLY_PASSWORD}
    hikari:
      auto-commit: false

  profiles:
    active: default,swagger

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

sipp:
  dissemination:
    schedule: ${DISSEMINATION_SCHEDULE:-}
    list-url: ${DISSEMINATION_LIST_URL}
    daysLastDisseminated: ${DAYS_LAST_DISSEMINATED:1}
  infoProduct:
    url: ${INFOPRODUCT_URL}

crossref:
  protocol: ${CROSSREF_PROTOCOL}
  host: ${CROSSREF_HOST}
  url: ${CROSSREF_URL}
  port: ${CROSSREF_PORT}
  username: ${CROSSREF_USERNAME}
  password: ${CROSSREF_PASSWORD}
  schema:
    url: ${CROSSREF_SCHEMA_URL}
  depositorEmail: ${CROSSREF_DEPOSITOR_EMAIL}

swagger:
  display:
    host: ${SWAGGER_DISPLAY_HOST}
    path: ${SWAGGER_DISPLAY_PATH}
    protocol: ${SWAGGER_DISPLAY_PROTOCOL}

pubs:
  lockTimeoutHours: ${PUBS_LOCK_TIMEOUT_HOURS}
  warehouseEndpoint: ${PUBS_WAREHOUSE_ENPOINT}
  authorities:
    authorized: ${PUBS_AUTHORIZED_GROUPS}
    spn: ${PUBS_SPN_GROUPS}

security:
  oauth2:
    resource:
      id: ${SECURITY_RESOURCE_ID}
      jwk:
        keySetUri: ${SECURITY_KEYSET_URI}

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /about
      exposure:
        include:
        - info
        - health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: never
